{
 "title": "CITA Cloud Node Exporter Dashboard",
 "description": "CITA Cloud Node Exporter Dashboard",
 "tags": [
  "Prometheus",
  "Exporter",
  "CITA Cloud"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(Node_Get_ServiceStatus,job)"
   },
   {
    "name": "node_id",
    "label": "NodeID",
    "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\"},NodeID) "
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\",NodeID=~\"$node_id\"},instance)"
   },
   {
    "name": "port",
    "label": "端口",
    "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\",NodeID=~\"$node_id\"},instance)"
   },
   {
    "name": "ChainName",
    "label": "ChainName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},ChainName)"
   },
   {
    "name": "Operator",
    "label": "Operator",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Operator)"
   },
   {
    "name": "TokenName",
    "label": "TokenName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenName)"
   },
   {
    "name": "TokenSymbol",
    "label": "TokenSymbol",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenSymbol)"
   },
   {
    "name": "Version",
    "label": "Version",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Version)"
   },
   {
    "name": "GenesisBlockNumberHash",
    "label": "GenesisBlockNumberHash",
    "query": "label_values(Node_Get_GenesisBlockNumberDetails{instance=~'$node:$port'},GenesisBlockNumberHash)"
   },
   {
    "name": "LastBlockNumberHash",
    "label": "LastBlockNumberHash",
    "query": "label_values(Node_Get_LastBlockNumberDetails,LastBlockNumberHash) "
   },
   {
    "name": "node_dir",
    "label": "Node Dir",
    "query": "label_values(Node_Get_DirInfo_TotalFileSize{instance=~'$node:$port'},NodeDir) "
   },
   {
    "name": "ConsensusStatus",
    "label": "ConsensusStatus",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},ConsensusStatus) "
   },
   {
    "name": "SoftVersion",
    "label": "SoftVersion",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},SoftVersion) "
   },
   {
    "name": "HostPlatform",
    "label": "HostPlatform",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},HostPlatform) "
   },
   {
    "name": "HostName",
    "label": "HostName",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},HostName) "
   },
   {
    "name": "NodeAddress",
    "label": "NodeAddress",
    "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodeAddress) "
   },
   {
    "name": "NodeIP",
    "label": "NodeIP",
    "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodeIP) "
   },
   {
    "name": "NodePort",
    "label": "NodePort",
    "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodePort) "
   },
   {
    "name": "MaxBlockNumber",
    "label": "MaxBlockNumber",
    "query": "query_result(max(Node_Get_LastBlockNumber{job=\"$job\"}))"
   },
   {
    "name": "timeRange",
    "label": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CITA Cloud Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "content": "<center>\n<br>\n<h1>$NodeAddress</h1>\n</center>"
  },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "content": "<center>\n<br>\n<h1>$SoftVersion</h1>\n</center>"
  },
  {
   "title": "gRPC Channel",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 4 },
   "content": "<center>\n<br>\n<h1>$NodeIP:$NodePort</h1>\n</center>"
  },
  {
   "title": "Peers Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_NodePeers{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last 1m TPS/s",
   "type": "singlestat",
   "description": "sum_over_time(Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$instance\"}[1m]) / 60",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}[1m]) / 60"
    }
   ]
  },
  {
   "title": "Last Block Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (Node_Get_LastBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
    }
   ]
  },
  {
   "title": "Last Block TX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block is Proposer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_CheckProposer{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_BlockDifference{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Avg Block Interval Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}[$__range])"
    }
   ]
  },
  {
   "title": "Block TX History",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Block Interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Local Voter History",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "1" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LocalVoter{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  { "title": "Chain Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network Run Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (Node_Get_GenesisBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
    }
   ]
  },
  {
   "title": "Genesis Block Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 29 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_GenesisBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Genesis Block Hash",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 9, "y": 29 },
   "content": "<center>\n<br>\n<h2>$GenesisBlockNumberHash</h2>\n</center>"
  },
  {
   "title": "Protocol Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "content": "<center>\n<br>\n<h2>$Version</h2>\n</center>"
  },
  {
   "title": "Last Block Number of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(Node_Get_LastBlockNumber{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Consensus Nodes of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(Node_Get_ChainNodes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Block Number of [ $ChainName ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Voting rate of consensus nodes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(Node_Get_VoteNode{job=\"$job\",NodeID=\"$node_id\"}[$__range]) * 100",
     "legendFormat": "{{Voter}}"
    }
   ]
  },
  {
   "title": "Consensus Node Vote Number of [ Block ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Block_Vote_Number{job=\"$job\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "CITA Cloud Node Exporter Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Hostname",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 45 },
   "content": "<center>\n<br>\n<h3>$HostName</h3>\n</center>"
  },
  {
   "title": "Host Platform",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 45 },
   "content": "<center>\n<br><br>\n<h3>$HostPlatform</h3>\n</center>"
  }
 ]
}