{
 "title": "Summary Dashboard",
 "description": "Summary Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cita-cli exporter 运行状态" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}} - {{job}}" }
   ]
  },
  {
   "title": "Last Block Number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "Node_Get_LastBlockNumber", "legendFormat": "{{NodeIP}}:{{NodePort}}" }
   ]
  },
  {
   "title": "Last Block Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberDetails"
    }
   ]
  }
 ]
}