# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockchain.proto',
  package='blockchain',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x62lockchain.proto\x12\nblockchain\"o\n\x0b\x42lockHeader\x12\x10\n\x08prevhash\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0e\n\x06height\x18\x03 \x01(\x04\x12\x19\n\x11transactions_root\x18\x04 \x01(\x0c\x12\x10\n\x08proposer\x18\x05 \x01(\x0c\"\x92\x01\n\x0bTransaction\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\n\n\x02to\x18\x02 \x01(\x0c\x12\r\n\x05nonce\x18\x03 \x01(\t\x12\r\n\x05quota\x18\x04 \x01(\x04\x12\x19\n\x11valid_until_block\x18\x05 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\r\n\x05value\x18\x07 \x01(\x0c\x12\x10\n\x08\x63hain_id\x18\x08 \x01(\x0c\",\n\x07Witness\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x0e\n\x06sender\x18\x02 \x01(\x0c\"\x85\x01\n\x15UnverifiedTransaction\x12,\n\x0btransaction\x18\x01 \x01(\x0b\x32\x17.blockchain.Transaction\x12\x18\n\x10transaction_hash\x18\x02 \x01(\x0c\x12$\n\x07witness\x18\x03 \x01(\x0b\x32\x13.blockchain.Witness\"X\n\x0fUtxoTransaction\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x13\n\x0bpre_tx_hash\x18\x02 \x01(\x0c\x12\x0e\n\x06output\x18\x03 \x01(\x0c\x12\x0f\n\x07lock_id\x18\x04 \x01(\x04\"\x8f\x01\n\x19UnverifiedUtxoTransaction\x12\x30\n\x0btransaction\x18\x01 \x01(\x0b\x32\x1b.blockchain.UtxoTransaction\x12\x18\n\x10transaction_hash\x18\x02 \x01(\x0c\x12&\n\twitnesses\x18\x03 \x03(\x0b\x32\x13.blockchain.Witness\"%\n\x10\x43ompactBlockBody\x12\x11\n\ttx_hashes\x18\x01 \x03(\x0c\"t\n\x0c\x43ompactBlock\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\'\n\x06header\x18\x02 \x01(\x0b\x32\x17.blockchain.BlockHeader\x12*\n\x04\x62ody\x18\x03 \x01(\x0b\x32\x1c.blockchain.CompactBlockBodyb\x06proto3'
)




_BLOCKHEADER = _descriptor.Descriptor(
  name='BlockHeader',
  full_name='blockchain.BlockHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prevhash', full_name='blockchain.BlockHeader.prevhash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='blockchain.BlockHeader.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='blockchain.BlockHeader.height', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactions_root', full_name='blockchain.BlockHeader.transactions_root', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proposer', full_name='blockchain.BlockHeader.proposer', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=143,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='blockchain.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='blockchain.Transaction.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to', full_name='blockchain.Transaction.to', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='blockchain.Transaction.nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quota', full_name='blockchain.Transaction.quota', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid_until_block', full_name='blockchain.Transaction.valid_until_block', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='blockchain.Transaction.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='blockchain.Transaction.value', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='blockchain.Transaction.chain_id', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=292,
)


_WITNESS = _descriptor.Descriptor(
  name='Witness',
  full_name='blockchain.Witness',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='blockchain.Witness.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='blockchain.Witness.sender', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=338,
)


_UNVERIFIEDTRANSACTION = _descriptor.Descriptor(
  name='UnverifiedTransaction',
  full_name='blockchain.UnverifiedTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='blockchain.UnverifiedTransaction.transaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_hash', full_name='blockchain.UnverifiedTransaction.transaction_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='witness', full_name='blockchain.UnverifiedTransaction.witness', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=474,
)


_UTXOTRANSACTION = _descriptor.Descriptor(
  name='UtxoTransaction',
  full_name='blockchain.UtxoTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='blockchain.UtxoTransaction.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_tx_hash', full_name='blockchain.UtxoTransaction.pre_tx_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='blockchain.UtxoTransaction.output', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lock_id', full_name='blockchain.UtxoTransaction.lock_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=564,
)


_UNVERIFIEDUTXOTRANSACTION = _descriptor.Descriptor(
  name='UnverifiedUtxoTransaction',
  full_name='blockchain.UnverifiedUtxoTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction', full_name='blockchain.UnverifiedUtxoTransaction.transaction', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_hash', full_name='blockchain.UnverifiedUtxoTransaction.transaction_hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='witnesses', full_name='blockchain.UnverifiedUtxoTransaction.witnesses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=710,
)


_COMPACTBLOCKBODY = _descriptor.Descriptor(
  name='CompactBlockBody',
  full_name='blockchain.CompactBlockBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hashes', full_name='blockchain.CompactBlockBody.tx_hashes', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=749,
)


_COMPACTBLOCK = _descriptor.Descriptor(
  name='CompactBlock',
  full_name='blockchain.CompactBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='blockchain.CompactBlock.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='blockchain.CompactBlock.header', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='blockchain.CompactBlock.body', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=751,
  serialized_end=867,
)

_UNVERIFIEDTRANSACTION.fields_by_name['transaction'].message_type = _TRANSACTION
_UNVERIFIEDTRANSACTION.fields_by_name['witness'].message_type = _WITNESS
_UNVERIFIEDUTXOTRANSACTION.fields_by_name['transaction'].message_type = _UTXOTRANSACTION
_UNVERIFIEDUTXOTRANSACTION.fields_by_name['witnesses'].message_type = _WITNESS
_COMPACTBLOCK.fields_by_name['header'].message_type = _BLOCKHEADER
_COMPACTBLOCK.fields_by_name['body'].message_type = _COMPACTBLOCKBODY
DESCRIPTOR.message_types_by_name['BlockHeader'] = _BLOCKHEADER
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['Witness'] = _WITNESS
DESCRIPTOR.message_types_by_name['UnverifiedTransaction'] = _UNVERIFIEDTRANSACTION
DESCRIPTOR.message_types_by_name['UtxoTransaction'] = _UTXOTRANSACTION
DESCRIPTOR.message_types_by_name['UnverifiedUtxoTransaction'] = _UNVERIFIEDUTXOTRANSACTION
DESCRIPTOR.message_types_by_name['CompactBlockBody'] = _COMPACTBLOCKBODY
DESCRIPTOR.message_types_by_name['CompactBlock'] = _COMPACTBLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockHeader = _reflection.GeneratedProtocolMessageType('BlockHeader', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKHEADER,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.BlockHeader)
  })
_sym_db.RegisterMessage(BlockHeader)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

Witness = _reflection.GeneratedProtocolMessageType('Witness', (_message.Message,), {
  'DESCRIPTOR' : _WITNESS,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.Witness)
  })
_sym_db.RegisterMessage(Witness)

UnverifiedTransaction = _reflection.GeneratedProtocolMessageType('UnverifiedTransaction', (_message.Message,), {
  'DESCRIPTOR' : _UNVERIFIEDTRANSACTION,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.UnverifiedTransaction)
  })
_sym_db.RegisterMessage(UnverifiedTransaction)

UtxoTransaction = _reflection.GeneratedProtocolMessageType('UtxoTransaction', (_message.Message,), {
  'DESCRIPTOR' : _UTXOTRANSACTION,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.UtxoTransaction)
  })
_sym_db.RegisterMessage(UtxoTransaction)

UnverifiedUtxoTransaction = _reflection.GeneratedProtocolMessageType('UnverifiedUtxoTransaction', (_message.Message,), {
  'DESCRIPTOR' : _UNVERIFIEDUTXOTRANSACTION,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.UnverifiedUtxoTransaction)
  })
_sym_db.RegisterMessage(UnverifiedUtxoTransaction)

CompactBlockBody = _reflection.GeneratedProtocolMessageType('CompactBlockBody', (_message.Message,), {
  'DESCRIPTOR' : _COMPACTBLOCKBODY,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.CompactBlockBody)
  })
_sym_db.RegisterMessage(CompactBlockBody)

CompactBlock = _reflection.GeneratedProtocolMessageType('CompactBlock', (_message.Message,), {
  'DESCRIPTOR' : _COMPACTBLOCK,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:blockchain.CompactBlock)
  })
_sym_db.RegisterMessage(CompactBlock)


# @@protoc_insertion_point(module_scope)
