# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2


class ConsensusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reconfigure = channel.unary_unary(
                '/consensus.ConsensusService/Reconfigure',
                request_serializer=common__pb2.ConsensusConfiguration.SerializeToString,
                response_deserializer=common__pb2.StatusCode.FromString,
                )
        self.CheckBlock = channel.unary_unary(
                '/consensus.ConsensusService/CheckBlock',
                request_serializer=common__pb2.ProposalWithProof.SerializeToString,
                response_deserializer=common__pb2.StatusCode.FromString,
                )


class ConsensusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reconfigure(self, request, context):
        """/ reconfigure consensus status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBlock(self, request, context):
        """/ check block validity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reconfigure': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconfigure,
                    request_deserializer=common__pb2.ConsensusConfiguration.FromString,
                    response_serializer=common__pb2.StatusCode.SerializeToString,
            ),
            'CheckBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBlock,
                    request_deserializer=common__pb2.ProposalWithProof.FromString,
                    response_serializer=common__pb2.StatusCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consensus.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsensusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reconfigure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consensus.ConsensusService/Reconfigure',
            common__pb2.ConsensusConfiguration.SerializeToString,
            common__pb2.StatusCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consensus.ConsensusService/CheckBlock',
            common__pb2.ProposalWithProof.SerializeToString,
            common__pb2.StatusCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
