# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consensus.proto',
  package='consensus',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63onsensus.proto\x12\tconsensus\x1a\x0c\x63ommon.proto\"T\n\x16\x43onsensusConfiguration\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x16\n\x0e\x62lock_interval\x18\x02 \x01(\r\x12\x12\n\nvalidators\x18\x03 \x03(\x0c\x32\x9d\x01\n\x10\x43onsensusService\x12H\n\x0bReconfigure\x12!.consensus.ConsensusConfiguration\x1a\x16.common.SimpleResponse\x12?\n\nCheckBlock\x12\x19.common.ProposalWithProof\x1a\x16.common.SimpleResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_CONSENSUSCONFIGURATION = _descriptor.Descriptor(
  name='ConsensusConfiguration',
  full_name='consensus.ConsensusConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='consensus.ConsensusConfiguration.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_interval', full_name='consensus.ConsensusConfiguration.block_interval', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validators', full_name='consensus.ConsensusConfiguration.validators', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['ConsensusConfiguration'] = _CONSENSUSCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsensusConfiguration = _reflection.GeneratedProtocolMessageType('ConsensusConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSCONFIGURATION,
  '__module__' : 'consensus_pb2'
  # @@protoc_insertion_point(class_scope:consensus.ConsensusConfiguration)
  })
_sym_db.RegisterMessage(ConsensusConfiguration)



_CONSENSUSSERVICE = _descriptor.ServiceDescriptor(
  name='ConsensusService',
  full_name='consensus.ConsensusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=131,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reconfigure',
    full_name='consensus.ConsensusService.Reconfigure',
    index=0,
    containing_service=None,
    input_type=_CONSENSUSCONFIGURATION,
    output_type=common__pb2._SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckBlock',
    full_name='consensus.ConsensusService.CheckBlock',
    index=1,
    containing_service=None,
    input_type=common__pb2._PROPOSALWITHPROOF,
    output_type=common__pb2._SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONSENSUSSERVICE)

DESCRIPTOR.services_by_name['ConsensusService'] = _CONSENSUSSERVICE

# @@protoc_insertion_point(module_scope)
