# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consensus.proto',
  package='consensus',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63onsensus.proto\x12\tconsensus\x1a\x0c\x63ommon.proto2\x92\x01\n\x10\x43onsensusService\x12\x41\n\x0bReconfigure\x12\x1e.common.ConsensusConfiguration\x1a\x12.common.StatusCode\x12;\n\nCheckBlock\x12\x19.common.ProposalWithProof\x1a\x12.common.StatusCodeb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONSENSUSSERVICE = _descriptor.ServiceDescriptor(
  name='ConsensusService',
  full_name='consensus.ConsensusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=45,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reconfigure',
    full_name='consensus.ConsensusService.Reconfigure',
    index=0,
    containing_service=None,
    input_type=common__pb2._CONSENSUSCONFIGURATION,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckBlock',
    full_name='consensus.ConsensusService.CheckBlock',
    index=1,
    containing_service=None,
    input_type=common__pb2._PROPOSALWITHPROOF,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONSENSUSSERVICE)

DESCRIPTOR.services_by_name['ConsensusService'] = _CONSENSUSSERVICE

# @@protoc_insertion_point(module_scope)
