# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import blockchain_pb2 as blockchain__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='executor.proto',
  package='executor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\x1a\x0c\x63ommon.proto\x1a\x10\x62lockchain.proto\"E\n\x0b\x43\x61llRequest\x12\n\n\x02to\x18\x01 \x01(\x0c\x12\x0c\n\x04\x66rom\x18\x02 \x01(\x0c\x12\x0e\n\x06method\x18\x03 \x01(\x0c\x12\x0c\n\x04\x61rgs\x18\x04 \x03(\x0c\"\x1d\n\x0c\x43\x61llResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x32y\n\x0f\x45xecutorService\x12/\n\x04\x45xec\x12\x11.blockchain.Block\x1a\x14.common.HashResponse\x12\x35\n\x04\x43\x61ll\x12\x15.executor.CallRequest\x1a\x16.executor.CallResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,blockchain__pb2.DESCRIPTOR,])




_CALLREQUEST = _descriptor.Descriptor(
  name='CallRequest',
  full_name='executor.CallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='executor.CallRequest.to', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from', full_name='executor.CallRequest.from', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='executor.CallRequest.method', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='executor.CallRequest.args', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=129,
)


_CALLRESPONSE = _descriptor.Descriptor(
  name='CallResponse',
  full_name='executor.CallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='executor.CallResponse.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['CallRequest'] = _CALLREQUEST
DESCRIPTOR.message_types_by_name['CallResponse'] = _CALLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALLREQUEST,
  '__module__' : 'executor_pb2'
  # @@protoc_insertion_point(class_scope:executor.CallRequest)
  })
_sym_db.RegisterMessage(CallRequest)

CallResponse = _reflection.GeneratedProtocolMessageType('CallResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLRESPONSE,
  '__module__' : 'executor_pb2'
  # @@protoc_insertion_point(class_scope:executor.CallResponse)
  })
_sym_db.RegisterMessage(CallResponse)



_EXECUTORSERVICE = _descriptor.ServiceDescriptor(
  name='ExecutorService',
  full_name='executor.ExecutorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=162,
  serialized_end=283,
  methods=[
  _descriptor.MethodDescriptor(
    name='Exec',
    full_name='executor.ExecutorService.Exec',
    index=0,
    containing_service=None,
    input_type=blockchain__pb2._BLOCK,
    output_type=common__pb2._HASHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='executor.ExecutorService.Call',
    index=1,
    containing_service=None,
    input_type=_CALLREQUEST,
    output_type=_CALLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTORSERVICE)

DESCRIPTOR.services_by_name['ExecutorService'] = _EXECUTORSERVICE

# @@protoc_insertion_point(module_scope)
