# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blockchain_pb2 as blockchain__pb2
import common_pb2 as common__pb2
import kms_pb2 as kms__pb2


class KmsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCryptoInfo = channel.unary_unary(
                '/kms.KmsService/GetCryptoInfo',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=kms__pb2.GetCryptoInfoResponse.FromString,
                )
        self.GenerateKeyPair = channel.unary_unary(
                '/kms.KmsService/GenerateKeyPair',
                request_serializer=kms__pb2.GenerateKeyPairRequest.SerializeToString,
                response_deserializer=kms__pb2.GenerateKeyPairResponse.FromString,
                )
        self.HashData = channel.unary_unary(
                '/kms.KmsService/HashData',
                request_serializer=kms__pb2.HashDataRequest.SerializeToString,
                response_deserializer=common__pb2.HashResponse.FromString,
                )
        self.VerifyDataHash = channel.unary_unary(
                '/kms.KmsService/VerifyDataHash',
                request_serializer=kms__pb2.VerifyDataHashRequest.SerializeToString,
                response_deserializer=common__pb2.StatusCode.FromString,
                )
        self.SignMessage = channel.unary_unary(
                '/kms.KmsService/SignMessage',
                request_serializer=kms__pb2.SignMessageRequest.SerializeToString,
                response_deserializer=kms__pb2.SignMessageResponse.FromString,
                )
        self.RecoverSignature = channel.unary_unary(
                '/kms.KmsService/RecoverSignature',
                request_serializer=kms__pb2.RecoverSignatureRequest.SerializeToString,
                response_deserializer=kms__pb2.RecoverSignatureResponse.FromString,
                )
        self.CheckTransactions = channel.unary_unary(
                '/kms.KmsService/CheckTransactions',
                request_serializer=blockchain__pb2.RawTransactions.SerializeToString,
                response_deserializer=common__pb2.StatusCode.FromString,
                )


class KmsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCryptoInfo(self, request, context):
        """Get crypto info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateKeyPair(self, request, context):
        """Generate a KeyPair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HashData(self, request, context):
        """Hash data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDataHash(self, request, context):
        """Verify hash of data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignMessage(self, request, context):
        """Sign a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverSignature(self, request, context):
        """Recover signature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTransactions(self, request, context):
        """check transactions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KmsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCryptoInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCryptoInfo,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=kms__pb2.GetCryptoInfoResponse.SerializeToString,
            ),
            'GenerateKeyPair': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKeyPair,
                    request_deserializer=kms__pb2.GenerateKeyPairRequest.FromString,
                    response_serializer=kms__pb2.GenerateKeyPairResponse.SerializeToString,
            ),
            'HashData': grpc.unary_unary_rpc_method_handler(
                    servicer.HashData,
                    request_deserializer=kms__pb2.HashDataRequest.FromString,
                    response_serializer=common__pb2.HashResponse.SerializeToString,
            ),
            'VerifyDataHash': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDataHash,
                    request_deserializer=kms__pb2.VerifyDataHashRequest.FromString,
                    response_serializer=common__pb2.StatusCode.SerializeToString,
            ),
            'SignMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SignMessage,
                    request_deserializer=kms__pb2.SignMessageRequest.FromString,
                    response_serializer=kms__pb2.SignMessageResponse.SerializeToString,
            ),
            'RecoverSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverSignature,
                    request_deserializer=kms__pb2.RecoverSignatureRequest.FromString,
                    response_serializer=kms__pb2.RecoverSignatureResponse.SerializeToString,
            ),
            'CheckTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTransactions,
                    request_deserializer=blockchain__pb2.RawTransactions.FromString,
                    response_serializer=common__pb2.StatusCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kms.KmsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KmsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCryptoInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/GetCryptoInfo',
            common__pb2.Empty.SerializeToString,
            kms__pb2.GetCryptoInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateKeyPair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/GenerateKeyPair',
            kms__pb2.GenerateKeyPairRequest.SerializeToString,
            kms__pb2.GenerateKeyPairResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HashData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/HashData',
            kms__pb2.HashDataRequest.SerializeToString,
            common__pb2.HashResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyDataHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/VerifyDataHash',
            kms__pb2.VerifyDataHashRequest.SerializeToString,
            common__pb2.StatusCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/SignMessage',
            kms__pb2.SignMessageRequest.SerializeToString,
            kms__pb2.SignMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecoverSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/RecoverSignature',
            kms__pb2.RecoverSignatureRequest.SerializeToString,
            kms__pb2.RecoverSignatureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kms.KmsService/CheckTransactions',
            blockchain__pb2.RawTransactions.SerializeToString,
            common__pb2.StatusCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
