# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='network.proto',
  package='network',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rnetwork.proto\x12\x07network\x1a\x0c\x63ommon.proto\"+\n\x15NetworkStatusResponse\x12\x12\n\npeer_count\x18\x01 \x01(\x04\"G\n\nNetworkMsg\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\x04\x12\x0b\n\x03msg\x18\x04 \x01(\x0c\"C\n\x0cRegisterInfo\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t2\xf5\x02\n\x0eNetworkService\x12\x32\n\x07SendMsg\x12\x13.network.NetworkMsg\x1a\x12.common.StatusCode\x12\x34\n\tBroadcast\x12\x13.network.NetworkMsg\x1a\x12.common.StatusCode\x12\x41\n\x10GetNetworkStatus\x12\r.common.Empty\x1a\x1e.network.NetworkStatusResponse\x12\x46\n\x19RegisterNetworkMsgHandler\x12\x15.network.RegisterInfo\x1a\x12.common.StatusCode\x12\x32\n\x07\x41\x64\x64Node\x12\x13.common.NodeNetInfo\x1a\x12.common.StatusCode\x12:\n\x0fGetPeersNetInfo\x12\r.common.Empty\x1a\x18.common.TotalNodeNetInfo2X\n\x18NetworkMsgHandlerService\x12<\n\x11ProcessNetworkMsg\x12\x13.network.NetworkMsg\x1a\x12.common.StatusCodeb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_NETWORKSTATUSRESPONSE = _descriptor.Descriptor(
  name='NetworkStatusResponse',
  full_name='network.NetworkStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_count', full_name='network.NetworkStatusResponse.peer_count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=83,
)


_NETWORKMSG = _descriptor.Descriptor(
  name='NetworkMsg',
  full_name='network.NetworkMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='network.NetworkMsg.module', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='network.NetworkMsg.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin', full_name='network.NetworkMsg.origin', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='network.NetworkMsg.msg', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=156,
)


_REGISTERINFO = _descriptor.Descriptor(
  name='RegisterInfo',
  full_name='network.RegisterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_name', full_name='network.RegisterInfo.module_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='network.RegisterInfo.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='network.RegisterInfo.port', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['NetworkStatusResponse'] = _NETWORKSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['NetworkMsg'] = _NETWORKMSG
DESCRIPTOR.message_types_by_name['RegisterInfo'] = _REGISTERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkStatusResponse = _reflection.GeneratedProtocolMessageType('NetworkStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKSTATUSRESPONSE,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.NetworkStatusResponse)
  })
_sym_db.RegisterMessage(NetworkStatusResponse)

NetworkMsg = _reflection.GeneratedProtocolMessageType('NetworkMsg', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKMSG,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.NetworkMsg)
  })
_sym_db.RegisterMessage(NetworkMsg)

RegisterInfo = _reflection.GeneratedProtocolMessageType('RegisterInfo', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERINFO,
  '__module__' : 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.RegisterInfo)
  })
_sym_db.RegisterMessage(RegisterInfo)



_NETWORKSERVICE = _descriptor.ServiceDescriptor(
  name='NetworkService',
  full_name='network.NetworkService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=228,
  serialized_end=601,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='network.NetworkService.SendMsg',
    index=0,
    containing_service=None,
    input_type=_NETWORKMSG,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Broadcast',
    full_name='network.NetworkService.Broadcast',
    index=1,
    containing_service=None,
    input_type=_NETWORKMSG,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNetworkStatus',
    full_name='network.NetworkService.GetNetworkStatus',
    index=2,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=_NETWORKSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterNetworkMsgHandler',
    full_name='network.NetworkService.RegisterNetworkMsgHandler',
    index=3,
    containing_service=None,
    input_type=_REGISTERINFO,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddNode',
    full_name='network.NetworkService.AddNode',
    index=4,
    containing_service=None,
    input_type=common__pb2._NODENETINFO,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPeersNetInfo',
    full_name='network.NetworkService.GetPeersNetInfo',
    index=5,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._TOTALNODENETINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORKSERVICE)

DESCRIPTOR.services_by_name['NetworkService'] = _NETWORKSERVICE


_NETWORKMSGHANDLERSERVICE = _descriptor.ServiceDescriptor(
  name='NetworkMsgHandlerService',
  full_name='network.NetworkMsgHandlerService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=603,
  serialized_end=691,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessNetworkMsg',
    full_name='network.NetworkMsgHandlerService.ProcessNetworkMsg',
    index=0,
    containing_service=None,
    input_type=_NETWORKMSG,
    output_type=common__pb2._STATUSCODE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORKMSGHANDLERSERVICE)

DESCRIPTOR.services_by_name['NetworkMsgHandlerService'] = _NETWORKMSGHANDLERSERVICE

# @@protoc_insertion_point(module_scope)
