# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='storage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rstorage.proto\x12\x07storage\x1a\x0c\x63ommon.proto\"5\n\x07\x43ontent\x12\x0e\n\x06region\x18\x01 \x01(\r\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"%\n\x06\x45xtKey\x12\x0e\n\x06region\x18\x01 \x01(\r\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x0c*\xca\x01\n\x07Regions\x12\n\n\x06GLOBAL\x10\x00\x12\x10\n\x0cTRANSACTIONS\x10\x01\x12\x0b\n\x07HEADERS\x10\x02\x12\n\n\x06\x42ODIES\x10\x03\x12\x0e\n\nBLOCK_HASH\x10\x04\x12\t\n\x05PROOF\x10\x05\x12\n\n\x06RESULT\x10\x06\x12!\n\x1dTRANSACTION_HASH2BLOCK_HEIGHT\x10\x07\x12\x1b\n\x17\x42LOCK_HASH2BLOCK_HEIGHT\x10\x08\x12\x15\n\x11TRANSACTION_INDEX\x10\t\x12\n\n\x06\x42UTTON\x10\n2\x9f\x01\n\x0eStorageService\x12\x31\n\x05Store\x12\x10.storage.Content\x1a\x16.common.SimpleResponse\x12\'\n\x04Load\x12\x0f.storage.ExtKey\x1a\x0e.storage.Value\x12\x31\n\x06\x44\x65lete\x12\x0f.storage.ExtKey\x1a\x16.common.SimpleResponseb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_REGIONS = _descriptor.EnumDescriptor(
  name='Regions',
  full_name='storage.Regions',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GLOBAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSACTIONS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HEADERS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BODIES', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_HASH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROOF', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSACTION_HASH2BLOCK_HEIGHT', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK_HASH2BLOCK_HEIGHT', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSACTION_INDEX', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUTTON', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=159,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_REGIONS)

Regions = enum_type_wrapper.EnumTypeWrapper(_REGIONS)
GLOBAL = 0
TRANSACTIONS = 1
HEADERS = 2
BODIES = 3
BLOCK_HASH = 4
PROOF = 5
RESULT = 6
TRANSACTION_HASH2BLOCK_HEIGHT = 7
BLOCK_HASH2BLOCK_HEIGHT = 8
TRANSACTION_INDEX = 9
BUTTON = 10



_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='storage.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='storage.Content.region', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='storage.Content.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='storage.Content.value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=93,
)


_EXTKEY = _descriptor.Descriptor(
  name='ExtKey',
  full_name='storage.ExtKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='storage.ExtKey.region', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='storage.ExtKey.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=132,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='storage.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='storage.Value.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
DESCRIPTOR.message_types_by_name['ExtKey'] = _EXTKEY
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.enum_types_by_name['Regions'] = _REGIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:storage.Content)
  })
_sym_db.RegisterMessage(Content)

ExtKey = _reflection.GeneratedProtocolMessageType('ExtKey', (_message.Message,), {
  'DESCRIPTOR' : _EXTKEY,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:storage.ExtKey)
  })
_sym_db.RegisterMessage(ExtKey)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:storage.Value)
  })
_sym_db.RegisterMessage(Value)



_STORAGESERVICE = _descriptor.ServiceDescriptor(
  name='StorageService',
  full_name='storage.StorageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=364,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='Store',
    full_name='storage.StorageService.Store',
    index=0,
    containing_service=None,
    input_type=_CONTENT,
    output_type=common__pb2._SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='storage.StorageService.Load',
    index=1,
    containing_service=None,
    input_type=_EXTKEY,
    output_type=_VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='storage.StorageService.Delete',
    index=2,
    containing_service=None,
    input_type=_EXTKEY,
    output_type=common__pb2._SIMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGESERVICE)

DESCRIPTOR.services_by_name['StorageService'] = _STORAGESERVICE

# @@protoc_insertion_point(module_scope)
