version: "3"
services:

  citamon_agent_host_exporter:
    image: prom/node-exporter:v0.18.0
    hostname: host_exporter
    container_name: citamon_agent_host_exporter
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/host/rootfs
      - /etc/localtime:/etc/localtime
    command: "--path.procfs='/host/proc' --path.sysfs='/host/sys' --path.rootfs='/host/rootfs'"
    networks:
      - citamon-agent-net

  citamon_agent_process_exporter:
    build:
      context: ./process-exporter/process-exporter.git
      dockerfile: Dockerfile
    image: citamon/agent-process-exporter:0.4.0
    hostname: process_exporter
    container_name: citamon_agent_process_exporter
    volumes:
      - /proc:/host/proc
      - ./process-exporter/config:/config
      - /etc/localtime:/etc/localtime
    command: "--procfs /host/proc --config.path /config/process_list.yml"
    networks:
      - citamon-agent-net

  citamon_agent_citacloud_exporter:
    build:
      context: ./citacloud-exporter
      dockerfile: Dockerfile
    image: citamon/agent-citacloud-exporter:20.2.2
    hostname: ${HOSTNAME}
    container_name: citamon_agent_citacloud_exporter
    pid: "host"
    volumes:
      - ${NODE_DATA_FOLDER}:${NODE_DATA_FOLDER}:ro
      - /etc/localtime:/etc/localtime
    command:
      - "--node-grpc-host"
      - "${NODE_GRPC_HOST}"
      - "--node-grpc-port"
      - "${NODE_GRPC_PORT}"
      - "--node-data-folder"
      - "${NODE_DATA_FOLDER}"
    networks:
      - citamon-agent-net

  citamon_agent_proxy_exporter:
    image: nginx:1.16.0
    hostname: proxy_exporter
    container_name: citamon_agent_proxy_exporter
    ports:
      - "1920:80"
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - citamon-agent-net

networks:
  citamon-agent-net:
