version: "3"
services:

  citamon_agent_process_exporter:
    build:
      context: ./process-exporter/
      dockerfile: Dockerfile
    image: citacloud/monitor-process-exporter:0.4.0
    hostname: process_exporter
    container_name: citamon_agent_process_exporter
    volumes:
      - /etc/localtime:/etc/localtime
    command:
      - "--procfs"
      - "/proc"
      - "--config.path"
      - "/config/process_list.yml"
    networks:
      - citamon-agent-net
    ports:
      - 49256:9256

  citamon_agent_citacloud_exporter:
    build:
      context: ./citacloud-exporter/
      dockerfile: Dockerfile
    image: citacloud/monitor-citacloud-exporter:0.1.0
    hostname: ${HOSTNAME}
    container_name: citamon_agent_citacloud_exporter
    volumes:
      - ${NODE_DATA_FOLDER}:${NODE_DATA_FOLDER}:ro
      - /etc/localtime:/etc/localtime
    command:
      - "--node-grpc-host"
      - "${NODE_GRPC_HOST}"
      - "--node-grpc-port"
      - "${NODE_GRPC_PORT}"
      - "--node-data-folder"
      - "${NODE_DATA_FOLDER}"
    networks:
      - citamon-agent-net
    ports:
      - 49349:9349

networks:
  citamon-agent-net:
